Add Actions In All Controllers
moise-mulungu/meet_doctor_back_end pull request #15
Opened 2022-08-14 12:04 UTC by samiullahbahadur

Hi Moise 
### I have did the below tasks:
I have change the user migrate( we need to add authenticate through react/redux instead of devise )
I have create all necessary actions in user controller
I have create all necessary actions in doctor controller  
I have create all necessary  actions in reservation controller

2022-08-14 13:40 UTC, moise-mulungu requested changes
Good job @samiullahbahadur for one more progress for this milestone.
![giphy (3)](https://user-images.githubusercontent.com/90564431/184539743-3dc36dd7-83d7-41b3-86f9-19f5cfa04041.gif)

You still have some changes to perform for the app to work perfectly:
- When I am trying to access a user page, there is an issue with rendering text/HTML format from the index action, please try to fix it.

2022-08-14 13:40 UTC, moise-mulungu commented on app/controllers/doctors_controller.rb
> +  before_action :set_Doctor, only: [:edit, :update, :show]
The following method `set-Doctor` is undefined when I am trying to access this path.
I suggest you could write `set_doctor` instead.

2022-08-15 08:24 UTC, moise-mulungu approved these changes
Congratulations @samiullahbahadur on fixing the required changes:
- API :heavy_check_mark: 
- Database :heavy_check_mark: 
_There is nothing else to say ... than just to merge_
_Happy coding :computer:_

2022-08-15 08:25 UTC, merged

2022-08-15 09:48 UTC, kosher9 commented
Hi @moise-mulungu , @samiullahbahadur , I hope you are doing well. I am doing better now. I just pulled the project and went through it. 
You guys did a great job. 👏🏾 👏🏾 👏🏾 

But I noticed a few things we should avoid: 
- We should not merge a commit without all linters green checked. ✅ 
- The tasks were not well structured therefore some 'actions' we will not need were created.

I am going to try my best to make the kanban more exhaustive and put some security rules. 

Thank you for your understanding guys. Happy coding and see you soon.